//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.09.28 at 12:50:37 PM CEST
//

package org.example.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@XmlType(
    propOrder = {
      "prd",
      "redirectLink",
      "tenant",
      "allowProvisional",
      "allowMemo",
      "user",
      "vector",
      "token",
      "password",
      "bearer",
      "wlaId"
    })
@XmlRootElement(name = "CNTRL")
@XmlAccessorType(XmlAccessType.FIELD)
public class Cntrl {

  @XmlElement(name = "PRD", required = true)
  private int prd;

  @XmlElement(name = "REDIRECTLINK")
  private String redirectLink;

  @XmlElement(name = "TENANT")
  private String tenant;

  @XmlElement(name = "ALLOW_PROVISIONAL")
  private int allowProvisional;

  @XmlElement(name = "ALLOW_MEMO")
  private int allowMemo;

  @XmlElement(name = "USER")
  private User user;

  @XmlElement(name = "VECTOR")
  private String vector;

  @XmlElement(name = "TOKEN")
  private String token;

  @XmlElement(name = "PASSWORD")
  private String password;

  @XmlElement(name = "BEARER")
  private String bearer;

  @XmlElement(name = "WLA_ID")
  private String wlaId;
}
