//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.09.28 at 12:35:42 PM CEST
//

package org.example.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "poa_values")
@XmlEnum
public enum PoaValues {
  Y,
  N,
  U,
  W,
  E;

  public String value() {
    return name();
  }

  public static PoaValues fromValue(String v) {
    return valueOf(v);
  }
}
